name: deploy-docs-site
on:
  push:
    # branches:
    # - main
    # - ci/deploy-docs-site
    tags:
      - 'v*.*.*' # Deploy on version tags, e.g. v1.0.0
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      # with:
      #   version: 10
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install and Build Docs ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm install
          pnpm --filter="*" run docs:build
      - name: Prepare Docs Folder ğŸ“‚
        run: |
          mkdir docs-site
          for file in ./packages/*
          do
              if test -d $file
              then
                mv $file/docs/.vitepress/dist docs-site/${file#./packages/}
              fi
          done
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-site
